[package]
name = "oakdb"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.21"
futures-util = { version = "0.3", default-features = false, features = ["sink", "std"] }
tokio = { version = "1.0.0", features = ["full"] }
tokio-tungstenite = "0.17.1"